name: Build Image
on:
  push:
    branches:
      - master
jobs:
  iterate-folders:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.set-images.outputs.images }}
    steps:
      - uses: actions/checkout@v2
      - id: set-images
        run: |
          set -ex;
          images=$(ls */*/Dockerfile | jq -R -s -c 'split("\n")[:-1] | map(sub("/Dockerfile$"; ""))');
          echo "::set-output name=images::$images"

  build:
    needs: iterate-folders
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: ${{ secrets.DOCKER_USERNAME }}
    strategy:
      matrix:
        image: ${{ fromJson(needs.iterate-folders.outputs.images) }}
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          ./build.sh ${{ matrix.image }}
